### ISSUE TITLE
the error of train.py

### ISSUE THREAD

**Issue by zyuxiang0822** [lpcccc-cv/MC-VarNet#2]
You're doing a fantastic job. I've tried running the code but encountered some issues. I hope to get a response from you. 
Traceback (most recent call last): 
File "train.py", line 253, in <module> main() 
File "train.py", line 162, in main model.optimize_parameters() 
File "/home/MC-VarNet-main/models/ref_rec_base_model.py", line 127, in optimize_parameters self.fake_1 = self.netG(self.im1_lr, self.im2_gt, self.mask) 
File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) 
File "/home/MC-VarNet-main/models/modules/VANet.py", line 192, in forward DC_x = self.data_consistency_layer(x_t0, x_k, mask) ## DC File "/home/MC-VarNet-main/models/modules/VANet.py", line 165, in data_consistency_layer output_complex = X_k + gene_complex * (1.0 - mask) 
RuntimeError: The size of tensor a (128) must match the size of tensor b (256) at non-singleton dimension 3

**Comment by Wuxiaomann** [comment]
Hi，I met the same problem. Could you please share how you fix it?
